services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq_service
    ports:
      - "${RABBITMQ_UI_PORT}:15672"
      - "${RABBITMQ_PORT}:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network

  weather_producer:
    build: ./producer
    container_name: weather_producer
    environment:
      DATA_SOURCE_BASE_URL: ${DATA_SOURCE_BASE_URL}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_QUEUE_NAME: ${RABBITMQ_QUEUE_NAME}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      LATITUDE: ${LATITUDE}
      LONGITUDE: ${LONGITUDE}
      TIMEZONE: ${TIMEZONE}

    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

volumes:
  rabbitmq_data:
